name: studioapp
favicon: null
layout_spectrum: 0.7443138025701046
typography_spectrum: 0.9583752257749438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6884036362171173
  lightness: 0.12050198786891997
  saturation: 0.7801911327987909
  rhythmicContrast: 0.7125284031499177
purpose: []
